admin:
  address:
    socket_address: { address: 127.0.0.1, port_value: 9800 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10099 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          generate_request_id: false
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: some_service
                  timeout: 180s
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              dynamic_stats: false
  clusters:
  - name: some_service
    connect_timeout: 180s
    type: STATIC
    lb_policy: LEAST_REQUEST
    circuit_breakers:
      thresholds:
        - max_connections: 4294967295
          max_pending_requests: 4294967295
          max_requests: 4294967295
          max_retries: 4294967295
          track_remaining: true
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        common_http_protocol_options:
          max_requests_per_connection: 4294967295
        use_downstream_protocol_config:
          http_protocol_options: {}
          http2_protocol_options: {}
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 4444
            hostname: app50ms
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 4445
            hostname: app100ms
