apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-pod1
spec:
  containers:
  - name: cpu-stress-container
    image: vish/stress
    args:
      - "-cpus"
      - "10"
      # - "--timeout"
      # - "30s" # Stress for 300 seconds (adjust as needed)
    resources:
      # requests:
      #   cpu: "2"      # Request 2 CPUs
      limits:
        cpu: "10"      # Limit to 2 CPUs
  tolerations:
    - key: "node"
      value: "node1"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/worker
            operator: In
            values:
            - node1
---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-pod2
spec:
  containers:
  - name: cpu-stress-container
    image: vish/stress
    args:
      - "-cpus"
      - "10"
      # - "--timeout"
      # - "30s" # Stress for 300 seconds (adjust as needed)
    resources:
      # requests:
      #   cpu: "2"      # Request 2 CPUs
      limits:
        cpu: "10"      # Limit to 2 CPUs
  tolerations:
    - key: "node"
      value: "node1"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/worker
            operator: In
            values:
            - node1