apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: ghcr.io/talha-waheed/generic-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
              protocol: TCP
      tolerations:
        - key: "node"
          value: "node2"
          effect: "NoSchedule"
        - key: "node"
          value: "node3"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - node2
                # - node3
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    app: app2
    service: app2
spec:
  type: NodePort
  ports:
  - port: 3333
    targetPort: 3333
  selector:
    app: app2