apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app3
  labels:
    app: app3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: app3
          image: ghcr.io/talha-waheed/generic-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
              protocol: TCP
      tolerations:
        - key: "node"
          value: "node1"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - node1
---
apiVersion: v1
kind: Service
metadata:
  name: app3
  labels:
    app: app3
    service: app3
spec:
  type: NodePort
  ports:
  - port: 3333
    targetPort: 3333
  selector:
    app: app3