apiVersion: v1
kind: Pod
metadata:
  name: hostagent-node0
  labels:
    app: hostagent-node0
spec:
  containers:
    - name: hostagent-node0
      image: talhawaheed/hostagent:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 9988
          protocol: TCP
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 0
      # resources:
      #   requests:
      #     cpu: 150m
      volumeMounts:
        - mountPath: /host
          name: host-filesystem
  volumes:
  - name: host-filesystem
    hostPath:
      path: /         # This will mount the root filesystem of the host
      type: Directory
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - minikube
---
apiVersion: v1
kind: Service
metadata:
  name: hostagent-node0
  labels:
    app: hostagent-node0
spec:
  type: NodePort
  ports:
  - port: 9988
    targetPort: 9988
  selector:
    app: hostagent-node0