# default namespace services
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin
  namespace: default
spec:
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST
---
# ingressgw
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin-svc0
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway-svc0
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin-svc1
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway-svc1
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin-svc2
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway-svc2
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin-svc3
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway-svc3
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin-svc4
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway-svc4
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin-svc5
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway-svc5
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin-svc6
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway-svc6
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin-svc7
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway-svc7
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin-svc8
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway-svc8
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin-svc9
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway-svc9
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin-svc10
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway-svc10
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin-svc11
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway-svc11
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin-svc12
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway-svc12
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin-svc13
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway-svc13
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mplb-wasm-plugin-svc14
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway-svc14
  url: oci://ghcr.io/talha-waheed/mplb-plugin:leastrequest_plus
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_POD_NAME
      valueFrom: HOST